#Requires -Version 7.0
param(
    [string]$ToolchainBin = 'D:\MYSY2\mingw64\bin',
    [string]$DeployDirectory = 'E:\zlowallpaper',
    [switch]$SkipTests
)
$ErrorActionPreference = 'Stop'
$frontend = Split-Path $PSScriptRoot -Parent
$build = Join-Path $frontend 'build'
$ToolchainBin = (Resolve-Path -LiteralPath $ToolchainBin).Path
$toolchainRoot = Split-Path $ToolchainBin -Parent
$deploy = [IO.Path]::GetFullPath($DeployDirectory)
if ($deploy -eq [IO.Path]::GetPathRoot($deploy)) { throw 'Deployment target cannot be a drive root' }
if ((Test-Path "$deploy/ZloWallpaper.exe") -and (Get-Process ZloWallpaper -ErrorAction SilentlyContinue)) {
    throw 'Close ZloWallpaper before replacing the runtime.'
}
$env:PATH = "$ToolchainBin;" + $env:PATH
function Checked([string]$Executable, [string[]]$Arguments) {
    & $Executable @Arguments
    if ($LASTEXITCODE -ne 0) { throw "$Executable failed with exit code $LASTEXITCODE" }
}
Checked 'cmake' @('-S', $frontend, '-B', $build, '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=Release', "-DCMAKE_CXX_COMPILER=$ToolchainBin/g++.exe", "-DQt6_DIR=$toolchainRoot/lib/cmake/Qt6")
Checked 'cmake' @('--build', $build, '--parallel', '4')
$webp = "$toolchainRoot/share/qt6/plugins/imageformats/qwebp.dll"
if (!(Test-Path $webp)) {
    $addon = "$frontend/deps/qt-imageformats"
    $webp = "$addon/mingw64/share/qt6/plugins/imageformats/qwebp.dll"
    if (!(Test-Path $webp)) { throw 'Missing WebP plugin. Install matching Qt imageformats or extract it to deps/qt-imageformats. See docs/FRONTEND.md.' }
    $qtVersion = & "$ToolchainBin/qmake6.exe" -query QT_VERSION
    $packageInfo = Get-Content -LiteralPath "$addon/.PKGINFO"
    if (!($packageInfo -match ('^pkgver = ' + [regex]::Escape($qtVersion) + '-'))) { throw 'Qt imageformats package must match the toolchain Qt version.' }
}
New-Item -ItemType Directory -Force -Path "$build/imageformats" | Out-Null
Copy-Item -LiteralPath $webp -Destination "$build/imageformats" -Force
if (!$SkipTests) { Checked 'ctest' @('--test-dir', $build, '--output-on-failure') }
New-Item -ItemType Directory -Force -Path $deploy | Out-Null
Copy-Item -LiteralPath "$build/ZloWallpaper.exe", "$build/libmpv-2.dll", "$build/ffmpeg.exe" -Destination $deploy -Force
foreach ($helper in @('icontra', 'translucenttb')) {
    New-Item -ItemType Directory -Force -Path "$deploy/$helper" | Out-Null
    if ($helper -eq 'icontra') {
        Get-ChildItem -LiteralPath "$build/icontra" | Where-Object { $_.Name -ne 'resources' } | Copy-Item -Destination "$deploy/icontra" -Recurse -Force
        New-Item -ItemType Directory -Force -Path "$deploy/icontra/resources" | Out-Null
        Get-ChildItem -LiteralPath "$build/icontra/resources" | Where-Object { $_.Name -ne 'lightwallpaper' } | Copy-Item -Destination "$deploy/icontra/resources" -Recurse -Force
        # Remove only an obsolete copy generated by an earlier build of this script.
        # It is not the original Asterol installation or a user wallpaper directory.
        $legacyCopy = [IO.Path]::GetFullPath((Join-Path $deploy 'icontra/resources/lightwallpaper'))
        if (Test-Path -LiteralPath $legacyCopy) {
            $resolvedCopy = (Resolve-Path -LiteralPath $legacyCopy).Path
            if ($resolvedCopy -ne $legacyCopy -or !$resolvedCopy.StartsWith($deploy + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase) -or (Get-Item -LiteralPath $legacyCopy).LinkType) {
                throw 'Unexpected legacy runtime path; refusing recursive removal.'
            }
            Remove-Item -LiteralPath $legacyCopy -Recurse -Force
        }
    } else {
        Get-ChildItem -LiteralPath "$build/$helper" | Copy-Item -Destination "$deploy/$helper" -Recurse -Force
    }
}
Checked "$ToolchainBin/windeployqt.exe" @('--release', '--compiler-runtime', '--no-translations', '--dir', $deploy, "$deploy/ZloWallpaper.exe")
Copy-Item -LiteralPath $webp -Destination "$deploy/imageformats" -Force
# MSYS2 Qt and plugins depend on non-Qt runtime DLLs. Recursively collect PE imports
# from the selected toolchain only; leave Windows API/system DLLs to the OS.
# Do not recurse into Electron/TranslucentTB and accidentally mix their runtimes.
$queue = [Collections.Generic.Queue[string]]::new()
$seen = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
Get-ChildItem -LiteralPath $deploy -File | Where-Object { $_.Extension -in '.dll', '.exe' } | ForEach-Object { $queue.Enqueue($_.FullName) }
foreach ($plugin in @('platforms', 'imageformats', 'styles', 'tls', 'networkinformation', 'multimedia', 'iconengines', 'generic')) {
    if (Test-Path "$deploy/$plugin") { Get-ChildItem -LiteralPath "$deploy/$plugin" -Recurse -File -Filter '*.dll' | ForEach-Object { $queue.Enqueue($_.FullName) } }
}
while ($queue.Count -gt 0) {
    $binary = $queue.Dequeue()
    if (!$seen.Add($binary)) { continue }
    $imports = & "$ToolchainBin/objdump.exe" -p $binary
    if ($LASTEXITCODE -ne 0) { throw "Cannot inspect PE imports: $binary" }
    foreach ($line in $imports) {
        if ($line -match 'DLL Name:\s+(\S+)') {
            $name = $Matches[1]
            $source = Join-Path $ToolchainBin $name
            $destination = Join-Path $deploy $name
            if (Test-Path -LiteralPath $source -PathType Leaf) {
                Copy-Item -LiteralPath $source -Destination $destination -Force
                $queue.Enqueue($destination)
            }
        }
    }
}
New-Item -ItemType Directory -Force -Path "$deploy/docs", "$deploy/licenses" | Out-Null
Get-ChildItem -LiteralPath "$frontend/docs" -File | Copy-Item -Destination "$deploy/docs" -Force
Copy-Item -LiteralPath "$frontend/LICENSE" -Destination "$deploy/licenses/ZloWallpaper-MIT.txt" -Force
Copy-Item -LiteralPath "$frontend/vendor/icontra/THIRD_PARTY_NOTICES.md" -Destination "$deploy/licenses/Icontra-notices.md" -Force
foreach ($package in @('qt6-base', 'qt6-multimedia', 'gcc-libs', 'libwebp')) {
    $source = "$toolchainRoot/share/licenses/$package"
    if (Test-Path $source) { Copy-Item -LiteralPath $source -Destination "$deploy/licenses" -Recurse -Force }
}
if (Test-Path "$frontend/deps/qt-imageformats/mingw64/share/licenses/qt6-imageformats") {
    Copy-Item -LiteralPath "$frontend/deps/qt-imageformats/mingw64/share/licenses/qt6-imageformats" -Destination "$deploy/licenses" -Recurse -Force
}
Copy-Item -LiteralPath "$PSScriptRoot/Launch-Demo.cmd" -Destination $deploy -Force
$records = Get-ChildItem -LiteralPath $deploy -Recurse -File | Where-Object { $_.Extension -in '.exe', '.dll', '.asar' } | ForEach-Object {
    [ordered]@{ path = [IO.Path]::GetRelativePath($deploy, $_.FullName).Replace('\', '/'); sizeBytes = "$($_.Length)"; sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant() }
}
$manifest = [ordered]@{ application = 'ZloWallpaper'; version = '0.2.0'; qtVersion = (& "$ToolchainBin/qmake6.exe" -query QT_VERSION); generatedAt = (Get-Date).ToUniversalTime().ToString('o'); files = @($records) }
# Generated build artifact, not hand-written source.
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath "$frontend/docs/runtime-manifest.json" -Encoding utf8
Copy-Item -LiteralPath "$frontend/docs/runtime-manifest.json" -Destination "$deploy/docs" -Force
Write-Host "Deployment complete: $deploy/ZloWallpaper.exe"
